package bdmigrate

import (
	"strings"
	"testing"

	"github.com/inhere/gofer/internal/tracker"
)

const bdInteg = "<!-- BEGIN BEADS INTEGRATION v:1 profile:minimal hash:abc -->\n## Beads Issue Tracker\nUse bd.\n<!-- END BEADS INTEGRATION -->\n"
const bdCodex = "<!-- BEGIN BEADS CODEX SETUP: generated by bd setup codex -->\nUse `bd ready`.\n<!-- END BEADS CODEX SETUP -->\n"

func TestEditInstructionFileKeepsOutsideContentAndPlacesGoferBlockInPlace(t *testing.T) {
	head, mid, tail := "# Title\n\n@workspace.md\n\n", "\nmiddle text\n\n", "\ntail without final newline"
	body := head + bdInteg + mid + bdCodex + tail
	out, plan, err := editInstructionFile(body, false, tracker.ManagedBlock())
	if err != nil {
		t.Fatal(err)
	}
	want := head + tracker.ManagedBlock() + mid + tail
	if out != want {
		t.Fatalf("got:\n%q\nwant:\n%q", out, want)
	}
	if plan.Action != "replace" || plan.Removed != 2 || !plan.Gofer {
		t.Fatalf("plan: %+v", plan)
	}
	// Idempotent: a second pass changes nothing.
	again, plan2, err := editInstructionFile(out, false, tracker.ManagedBlock())
	if err != nil || again != out || plan2.Action != "none" {
		t.Fatalf("second pass: %q %+v %v", again, plan2, err)
	}
}

func TestEditInstructionFileSkipGoferAndExistingGoferBlock(t *testing.T) {
	body := "@AGENTS.md\n" + bdInteg + "tail\n"
	out, plan, err := editInstructionFile(body, true, tracker.ManagedBlock())
	if err != nil || out != "@AGENTS.md\ntail\n" || plan.Action != "remove" || plan.Gofer {
		t.Fatalf("skip: %q %+v %v", out, plan, err)
	}
	// A file that already carries the gofer block just loses the bd block.
	body = tracker.ManagedBlock() + "x\n" + bdInteg
	out, plan, err = editInstructionFile(body, false, tracker.ManagedBlock())
	if err != nil || out != tracker.ManagedBlock()+"x\n" || plan.Action != "remove" {
		t.Fatalf("existing: %q %+v %v", out, plan, err)
	}
}

func TestEditInstructionFileAppendAndCRLFAndIncomplete(t *testing.T) {
	out, plan, err := editInstructionFile("no blocks here", false, tracker.ManagedBlock())
	if err != nil || !strings.HasPrefix(out, "no blocks here\n"+tracker.BeginBlock) || plan.Action != "append" {
		t.Fatalf("append: %q %+v %v", out, plan, err)
	}
	crlf := "a\r\n" + strings.ReplaceAll(bdInteg, "\n", "\r\n") + "b\r\n"
	out, _, err = editInstructionFile(crlf, false, tracker.ManagedBlock())
	if err != nil || !strings.HasPrefix(out, "a\r\n"+tracker.BeginBlock+"\r\n") || !strings.HasSuffix(out, "\r\nb\r\n") || strings.Contains(strings.ReplaceAll(out, "\r\n", ""), "\n") {
		t.Fatalf("CRLF file must keep CRLF endings: %q", out)
	}
	if _, _, err := editInstructionFile("x\n<!-- BEGIN BEADS INTEGRATION v:1 -->\nno end\n", false, tracker.ManagedBlock()); err == nil {
		t.Fatal("an unterminated block must be an error, not a silent truncation")
	}
}
